#!/bin/bash
# $Header: /home/eschnett/C/carpet/Carpet/CarpetAttic/Cart3dTest/utils/cmptest,v 1.4 2001/04/23 08:10:17 schnetter Exp $

# Call this script from the Cactus directory.  It compares a Carpet
# ASCII testsuite output to PUGH ASCII testsuite output.

for suite in $(ls TEST/carpet | grep -v log\$); do
    
    echo
    echo "Suite: $suite"
    
    for file in $(ls arrangements/AlphaThorns/Cart3dTest/test/$suite | grep -v CVS | grep -v \.dl); do
	
	paste \
	    <( awk 'NF==2 { print $2; }' arrangements/AlphaThorns/Cart3dTest/test/$suite/$file ) \
	    <( awk 'NF==9 { print $9; }' TEST/carpet/$suite/$file ) \
	| awk '{ diff=(($1-$2)/($1+$2+1e-6))**2; if (diff>1e-10) { ++cnt; print l+0,$1,$2,diff; ++l; } } END { if (cnt>0) print "File '$file'",cnt+0,"differing lines"; }'
	
    done
    
done

echo "Done."
